### ISSUE TITLE
Date selection bar / weather graph axis is off by a day or two.

### ISSUE THREAD

**Issue by jetpack** [unicef/carrotjuice2#25]
There's something wrong with the x axis on our date selection bar / weather graph. For example, given data for January 4 to January 5, the graph seems to show the data as being from January 2 to January 3.

I thought it was just a UTC/timezone thing, but I still had the same problem even after making a bunch of things UTC.

Step 1 is to get a minimal test case with just d3, separate from carrotjuice code.

**Comment by mikefab** [comment]
transform:translate was used in class axis but not class time-series.

translate(30, 0) now applied to time-series in branch mikefab-align-chart.
